---
- name: apply smtp secret to k8s
  hosts: tag_Name_Master
  become: true
  tasks:

  - name: 產生 smtp srcret
    ansible.builtin.template:
      src: ./grafana-smtp-secret.yaml.j2
      dest: ./grafana-smtp-secret.yaml
      mode: '0644'
  
  - name: apply grafana-smtp-secret.yaml
    command: kubectl create -f ./grafana-smtp-secret.yaml
    environment:
      KUBECONFIG: /home/ubuntu/.kube/config