kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-nfs-pv
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client